[project]
name = "torch_candle"
version = "0.1.0"
description = "A PyTorch-compatible API with Candle backend"
readme = "README.md"
authors = [
    { name = "Hem", email = "[EMAIL_ADDRESS]" }
]
dependencies = [
    "numpy",
    "pytest>=8.3.5",
]
requires-python = ">=3.8, <3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Rust",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "License :: OSI Approved :: MIT License",
]

[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "torch_candle_backend"
manifest-path = "rust/Cargo.toml"
python-packages = ["torch_candle"]

[tool.pytest.ini_options]
pythonpath = ["src"]
